### ISSUE TITLE
Problem building docker image

### ISSUE THREAD

**Issue by jonico** [WGierke/git_better#63]
@Baschdl: When trying to build your docker image, I get the following stack trace:

```
Step 12 : RUN python server/manage.py migrate
 ---> Running in d4a8f66ecac8
Traceback (most recent call last):
  File "server/manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/site-packages/social/apps/django_app/default/models.py", line 1, in <module>
    from social_django.models import AbstractUserSocialAuth, UserSocialAuth, Nonce, Association, Code, DjangoStorage
ImportError: No module named social_django.models
````

**Comment by Baschdl** [comment]
@jonico We will look into this

**Comment by WGierke** [comment]
@jonico Sorry for the inconvenience, apparently there were some breaking changes between dependency upgrades. It should work now. Have a nice weekend!
